package org.jcramb.stackrefresh.book.repository;

import java.util.List;

import org.jcramb.stackrefresh.book.model.BookModel;


/**
 * Custom interface that provides operations that aren't generated by spring-data-jpa by default.
 * 
 * @author Jamie Cramb
 */
public interface BookRepositoryCustom {

    List<BookModel> getBooksByNameAndAuthorContains(String nameContains, String authorContains);
}